### ISSUE TITLE
Can pybetter support click 8.x ?

### ISSUE THREAD

**Issue by sreerajkksd** [lensvol/pybetter#128]
Looks like there is a hard dependency on click 7.x on the installation docs. Can we make it support click 8 as well ?
(PS: I'm almost sure that it works, so we might need to make it explicit on the configs. )

**Comment by lensvol** [comment]
I think it can be done. Is there any specific reason for the upgrade to happen?

**Comment by sreerajkksd** [comment]
Nothing specific!

we use a virtual environment for our tool that need both click and pybetter. Installing pybetter downgraded click and that is not what we want. I could fix it by reinstalling click==8.0.3 but just wanted to point this out.

**Comment by paw-lu** [comment]
Just to add to this, simply removing the constraint on click would be enough to solve these problems

```diff
```

**Comment by lensvol** [comment]
I've just released version 0.4.1 which bumps the required `click` version from 7 to 8. Please give it a try and report if it still does not work for you!

P.S. Sorry for the delay, global chaos has had detrimental effects on my creativity. :(

**Comment by paw-lu** [comment]
Nothing to be sorry about at all. Grateful for the work shared here! Take your time!
