### ISSUE TITLE
B007 f-string fixed breaks files by changing quote types

### ISSUE THREAD

**Issue by Zac-HD** [lensvol/pybetter#60]
For example, running `pybetter --select=B007 example.py` on the following file

```python
f"""
no substitutions
"""

f'"'
```

produces

```python
"
no substitutions
"

"""
```

which is obviously invalid syntax in each case.  This can be fixed by preserving the string quotes in each case, i.e. *only* discarding the `f`-prefix.  Note that raw strings such as `rf"\"` or `fr'\k'` mean that you can't just discard the whole prefix either.

You might find my [Hypothesmith](https://github.com/Zac-HD/hypothesmith) library useful, as it can be used to generate arbitrary (and very weird) source code to test against:

```python
from hypothesis import given
from hypothesmith import from_node
from libcst import FormattedString

@given(from_node(FormattedString))
def test_fstrings_are_formatted_correctly(source_code: str) -> None:
    refactored = ...  # Call the refactoring code here
    compile(refactored, "<string>", "exec")  # Check that our output is still valid code:
```

Found via a downstream bug report in https://github.com/Zac-HD/shed/pull/9.  So thanks for PyBetter - it's so useful that I'm incorporating it in other tools!

**Comment by lensvol** [comment]
Thank you for reporting this!

I will try to fix it ASAP. :)

(`Hypothesmith` is quite awesome from the first glance, kudos!)

**Comment by Zac-HD** [comment]
You're welcome, thank you, and thank you!

**Comment by lensvol** [comment]
Will release the new version in a couple of days. :)
